### ISSUE TITLE
Will it work for lengthy values?

### ISSUE THREAD

**Issue by jayudhandha** [Codearte/props2yaml#20]
I am converting it my map into yaml.

Map: `{management.endpoints.web.exposure.include= health, info, refresh, shutdown, selftest, listProcessors}`

Output of code **Props2YAML.fromContent(yaml.dump(Map)).convert()**

**Expected Output:**

```
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, shutdown, selftest, listProcessors
```

**Actual Output:**

```
listProcessors: ''
management:
    endpoints:
        web:
            exposure:
                include: health, info, refresh, shutdown, selftest,

```

Note: 

> If i remove `listProcessors` from the map value than it's working fine.

I tried to play with this map in my sample file with below code

```
Props2YAML pr = new Props2YAML(yaml.dump(Map));

System.out.println(pr.convert());

```

This is giving me correct output.

Why i can't make it work with the code `Props2YAML.fromContent(yaml.dump(Map)).convert()` ?(Which is mentioned in README)

Thanks,
Jayesh
