### ISSUE TITLE
no support for list of props

### ISSUE THREAD

**Issue by maciekpe** [Codearte/props2yaml#3]
```
logs.config[1].skipAll = false
logs.config[1].methodPattern = POST

```

expected:

```
logs:
   config:
      - skipAll: true
        methodPattern: ".*"

```
